module.exports = {
  MIN_MATCH_WAITTIME: 15, //THIS IS IN SECONDS
  MATCH_LENGTH: 5, //IN MINUTES
  MAX_MATCHES: 5,
  BOOST_STRENGTH: 2.5, //multiplier to max velocity
  DEFAULT_NAME: "Car",
  WORLD_WIDTH: 3000,
  WORLD_HEIGHT: 2000,
}